### ISSUE TITLE
Unable to attach to INPUT-only pins

### ISSUE THREAD

**Issue by vortigont** [rwmingis/InterruptButton#1]
esp32 has 4 INPUT-only pins 34,35,36,39 that can't be set with PULLUP or PULLDOWN
due to this condition those pins are not working for this lib.
```
void InterruptButton::begin(void){
  if(m_pinMode == INPUT_PULLUP || m_pinMode == INPUT_PULLDOWN) {}
```
https://github.com/rwmingis/InterruptButton/blob/13d009f9ccbed23c01cef76a6a42256340f252a3/InterruptButton.cpp#L28

might be possible to add `|| m_pinMode == INPUT` here to use those pins also?

**Comment by rwmingis** [comment]
Yep, good catch, have done just that and updated.  Cheers.  Will leave to the user to implement correctly.

**Comment by vortigont** [comment]
Thanks for quick fix! Nice, lib you have here, BTW :)

**Comment by rwmingis** [comment]
No worries, thanks for the kind words!
