### ISSUE TITLE
Program crashes

### ISSUE THREAD

**Issue by davidzhu210** [rwmingis/InterruptButton#15]
Hi I often encounter this issue and my ESp32 will reboot:

assert failed: xQueueGenericSend queue.c:832 (pxQueue->pcHead != ((void *)0) || pxQueue->u.xSemaphore.xMutexHolder == ((void *)0) || pxQueue->u.xSemaphore.xMutexHolder == xTaskGetCurrentTaskHandle())

Why?

**Comment by rwmingis** [comment]
Hi,

I have not seen this before, but haven't seen your code either so can't be sure.  But 2 things come to mind.  

1. If your routine that you bind to the button is too big, i may be too much for the RTOS handler with the amount of stack reserved for this library.  If you want to change it then modify this line in your instance of the library to set aside more memory:

https://github.com/rwmingis/InterruptButton/blob/2331071e14f82f9937dca66f1268496cb62a0a1a/InterruptButton.cpp#L39

I had it on my list to make this value user configurable when creating the object, just looks like I haven't quite gotten there yet.

2. Potentially you could get crashes when deleting dynamically created instances of the interrupt button object, but I have put in some code to prevent this from happening if deleted mid-press say.

Let me know if either fixes your issue..
