### ISSUE TITLE
RTOS API

### ISSUE THREAD

**Issue by davidzhu210** [rwmingis/InterruptButton#16]
I need to use RTOS API in the event fucntion. For example, sending some data to a queue, should I use regular API, or API with _FromISR?
xQueueOverwrite(QueueHandle_t xQueue, const void * pvItemToQueue);
xQueueOverwriteFromISR(QueueHandle_t xQueue, const void * pvItemToQueue，BaseType_t *pxHigherPriorityTaskWoken);
Thanks.

**Comment by rwmingis** [comment]
I think just the regular version since the event pocedures are called from
an RTOS task, not directly from the ISR.

**Comment by davidzhu210** [comment]
Got it. Thank you!

Thanks,
David
________________________________
